### ISSUE TITLE
Could you modify the code for the plugin so that it automatically adds "&has_verified=1&bpctr=9999999999" when first loading any YouTube video page, rather than after detecting a content discretion warning?

### ISSUE THREAD

**Issue by rjdg14** [ba32107/youtube-auto-proceed#14] opened 2021-06-18 11:04 UTC
As of now, your plugin seems to work along the lines of the following:

- A YouTube video page will be loaded normally with the default URL
- If the video is age restricted and the user is logged in the viewer discretion warning will appear. After about a second or two, the plugin will kick in and add "&has_verified=1&bpctr=9999999999" to the end of the video URL
- The added string will disappear from the URL after about a second and the video will then load normally

I feel that the second step, whereby YouTube will still hang for about a second at the warning, could be circumvented altogether if the plugin was altered to automatically add the "&has_verified=1&bpctr=9999999999" string to every video URL when first clicked, regardless of whether it's an age restricted video or not. Currently if I want to skip the warning altogether, I need to copy the video URL into the address bar and then paste the string to the end of it manually.

**Comment by ba32107** [comment] 2021-06-18 18:49
Yes, you are correct, this is the way the extension works. 

I understand your suggestion, however, implementation-wise it's not so simple. The extension is triggered whenever a tab is loaded or activated with a `youtube.com` URL. Therefore, implementing your idea would only be possible by automatically redirecting the normal URL (without the extra args) to the one that skips the warning. This means that _every single video_ you watch would be redirected at least once, whether or not it has a warning. This adds an enormous, unnecessary overhead and would rightly annoy users.

The only way I see to implement your suggestion is by parsing every link on the current page you're on, and add the extra args to each link _before_ the user clicks it. This would require asking permissions for the extension to all pages (not just `youtube.com`), not to mention a complete rewrite of the extension. This is not something I'd like to do.

If I understand correctly, the root cause of your request is to get rid of the slight, few-second delay before the redirect happens. I'm not sure I can do anything about that, I spent a lot of time adding a few small tweaks and delays to make sure the extension actually works. If you can optimize it somehow, feel free to raise a PR - until then, I'm going to close this.

**Closed as completed by ba32107** 2021-06-18 18:49 UTC
